- api/dbinit/team/data.js
>  DB 초기화 코드 최종버전 추가

- src/components/layout/Header.jsx
- src/pages/About.jsx
- src/pages/ErrorPage.jsx
- src/pages/SignUp.jsx
- src/pages/mypage/seller/SellerMyPageHeader.jsx
- src/pages/mypage/user/UserMypageHeader.jsx
- src/routes.jsx
🚚 Rename: 라우트 경로 설정 및 해당 연결 파일 경로 수정
mypage 경로 오류 해결 필요
> 🚚 Rename: 라우트 경로 설정 및 해당 연결 파일 경로 수정

- src/index.css
- src/pages/SellerInfo.jsx
- src/pages/SellerInfoEdit.jsx
- src/pages/UserInfo.jsx
- src/pages/UserInfoEdit.jsx
- src/pages/mypage/seller/SellerSalesList.jsx
- src/pages/mypage/seller/SellerSalesListItem.jsx
- src/pages/mypage/user/UserOrderListItem.jsx
- src/pages/mypage/user/UserReviewList.jsx
- src/pages/mypage/user/UserWishListItem.jsx
mypage - user, seller 전체 페이지 컴포넌트 수정완료
> mypage - user, seller 전체 페이지 컴포넌트 수정완료 

- index.html
- src/components/layout/Header.jsx
- src/pages/Cart.jsx
- src/pages/Login.jsx
- src/pages/Mainpage.jsx
- src/pages/SignUp.jsx
- src/pages/magazine/MagazineDetail.jsx
- src/pages/magazine/MagazineListItem.jsx
- src/pages/market/MarketListItem.jsx
- src/pages/mypage/seller/SellerMyPageHeader.jsx
- src/pages/mypage/seller/SellerUploadProduct.jsx
- src/pages/mypage/user/UserMypageHeader.jsx
- src/routes.jsx
🚚 Rename: 유저/셀러 마이페이지 라우트 경로 설정 추가 보수, 하위페이지 a태그 -> Link to로 변경 완료
> 🚚 Rename: 라우트 경로 설정 추가 보수, 하위페이지 a태그 -> Link to로 변경 완료

- src/pages/mypage/seller/SellerMyPageHeader.jsx
- src/pages/mypage/seller/SellerUploadProduct.jsx
- src/pages/mypage/user/UserMypageHeader.jsx
- src/pages/mypage/user/UserReviewItem.jsx
user, seller Header 컴포넌트 title 이슈 수정 완료
> user, seller Header 컴포넌트 title 이슈 수정 완료

- src/components/layout/Header.jsx
Rename: 로고 클릭시 메인페이지로 이동하는 라우터 경로 수정
> 🚚 Rename: 로고 클릭시 메인페이지로 이동하는 라우터 경로 수정

- src/components/layout/Header.jsx
- src/pages/Login.jsx
- src/zustand/store.js
> feat:토큰 저장 및 헤더 메뉴 로그인 유무로 텍스트 변경

- api/API-Client/01.로그인/일반 회원 로그인(_id=4).bru
- src/pages/mypage/user/UserReviewItem.jsx
- src/pages/mypage/user/UserReviewList.jsx
[✨ Feat: 마이페이지 리뷰리스트 화면 렌더링 작업 완료]
> ✨ Feat: 마이페이지 리뷰리스트 화면 렌더링 작업 완료

- .env
> ✨ Feat: .env 파일 추가

- api/dbinit/team/data.js
edit : DB orderList userId 2 내용 추가
> edit : DB orderList userId 2 내용 추가

- api/dbinit/team/data.js
edit : DB orderlist 이미지 파일 경로 수정
> 🚧 edit : DB orderlist 이미지 파일 경로 수정

- src/index.css
- src/pages/CartList.jsx
- src/pages/CartListItem.jsx
checkbox 기능 추가 중 하나의 아이템 선택 해제시 전체선택 해제되지 않는 이슈 발생
>  Feat: CartList 삭제, checkbox 기능 추가

- api/dbinit/team/data.js
- DB user extra imge 경로 추가 및 엑박이미지 경로 수정
> edit : DB user extra imge 경로 추가 및 엑박이미지 경로 수정

- api/dbinit/team/data.js
> 🚧 edit : DB orderlist 파일 경로 수정

- src/pages/Mainpage.jsx
- src/pages/market/MarketDetail.jsx
- src/pages/market/MarketList.jsx
- src/pages/market/MarketListItem.jsx
> 🚧 edit : Market 이미지 경로 수정

- src/components/layout/Header.jsx
> 🚧 edit: 주석 수정

- src/pages/PaymentComplete.jsx
- src/pages/cart/CartList.jsx
- src/pages/cart/CartListItem.jsx
- src/pages/market/MarketDetail.jsx
- src/pages/market/MarketListItem.jsx
- Feat: 상품 디테일 페이지, 카트 재고조회 기능 추가 
- Feat: 마켓 상세페이지, 카트 내에서 구매기능 결제페이지에 렌더링
- edit : 상품 상세페이지, 카트 컴포넌트 내 불필요한 콘솔, 변수 삭제
> Feat: 상품 디테일 페이지, 카트 재고조회 기능 추가 

- package-lock.json
- package.json
- src/pages/market/MarketDetail.jsx
- src/pages/market/MarketList.jsx
- edit : 북마크 기능 수정
-  Feat: 마켓페이지 sort 기능 추가
> edit : 북마크 기능 수정

- src/pages/market/MarketList.jsx
- src/pages/mypage/seller/SellerMyPageHeader.jsx
- src/pages/mypage/seller/SellerUploadProduct.jsx
>  edit : 마켓 sort option 이슈 수정

- README.md
> 📝 Docs: gif 파일 추가

- README.md
- src/components/layout/Header.jsx
- src/pages/market/MarketList.jsx
🚧 edit : 마켓 sort 기능 api로 수정 완료
✨ Feat: Header에 카트 수량 보여주기 기능
> 🚧 edit : 마켓 sort 기능 api로 수정 완료 

- src/components/layout/Footer.jsx
- src/components/layout/Header.module.css
- src/components/layout/Modal.jsx
- src/components/layout/Modal.module.css
- src/index.css
- src/pages/About.jsx
- src/pages/Login.jsx
- src/pages/Mainpage.jsx
- src/pages/Payment/Payment.module.css
- src/pages/Payment/PaymentComplete.jsx
- src/pages/Payment/PaymentProcess.jsx
- src/pages/SignUp.jsx
- src/pages/magazine/MagazineDetail.jsx
- src/pages/magazine/MagazineList.jsx
- src/pages/market/Market.module.css
- src/pages/market/MarketDetail.jsx
- src/pages/market/MarketList.jsx
- src/pages/mypage/seller/SellerMyPageHeader.jsx
- src/pages/mypage/user/UserMypageHeader.jsx
🚧 edit : 최종 QA 수정 내용 적용
- background, header 이슈 해결
> 🚧 edit : 최종 QA 수정 내용 적용
